# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'faileann'
  imageRepository: 'client'
  containerRegistry: 'failean.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'failean12fa-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Name of the new namespace being created to deploy the PR changes.
  k8sNamespaceForPR: 'review-app-$(System.PullRequest.PullRequestId)'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - script: az acr login --name failean --username $(registryUserName) --password $(registryPassword)
            displayName: 'Login to ACR'
          - task: Docker@2
            inputs:
              command: 'build'
              repository: 'failean.azurecr.io/client'
              dockerfile: '**/Dockerfile'
              buildContext: '$(Build.Repository.LocalPath)'
              arguments: '--build-arg NPMTOKEN=$(npmToken)'
              tags: |
                $(tag)
          - task: Docker@2
            inputs:
              command: 'push'
              repository: 'failean.azurecr.io/client'
              tags: |
                $(tag)

          - upload: manifests
            artifact: manifests
