trigger:
  - main # Branch to trigger the build

variables:
  imageName: 'client'
  tag: 'latest'
  registry: 'failean.azurecr.io'

stages:
  - stage: Build
    displayName: 'Build stage'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NpmAuthenticate@0
            inputs:
              workingFile: '.npmrc'  # Assumes your .npmrc file is in the root directory
              customEndpoint: 'YOUR_NPM_SERVICE_CONNECTION_NAME' # The name of the npm service connection to use

          - task: Docker@2
            inputs:
              command: 'build'
              repository: '$(registry)/$(imageName)'
              dockerfile: '**/Dockerfile'
              buildContext: '$(Build.Repository.LocalPath)'
              tags: |
                $(tag)
